[build]
  command = "npm run build:client"
  publish = "dist/public"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 5173

[redirects]
  # Single Page App fallback: serve index.html for all non-file routes
  from = "/*"
  to = "/index.html"
  status = 200