[build]
  command = "npm run build:client"
  publish = "dist/public"

[build.environment]
  # Avoid forcing NODE_ENV to production during Netlify build so devDependencies install.
  # Netlify will use the Node version from package.json `engines` when available.

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  # Single Page App fallback: serve index.html for all non-file routes
  from = "/*"
  to = "/index.html"
  status = 200